name: Node.js Package

on:
  push:
    branches:
      - main # ou la branche de votre choix

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          scope: "@mattlegrizzly"
      - run: npm install
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.arcopole-npm-package}}
